In [2]:
import pandas as pd
import matplotlib.pyplot as plt
# Cargar los datos desde el archivo parquet

In [3]:
df = pd.read_parquet("yellow_tripdata_2025-01.parquet")
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [4]:
df.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          540149
trip_distance                 0
RatecodeID               540149
store_and_fwd_flag       540149
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     540149
Airport_fee              540149
cbd_congestion_fee            0
dtype: int64

In [5]:
(df.isnull().sum() / len(df)) * 100

VendorID                  0.000000
tpep_pickup_datetime      0.000000
tpep_dropoff_datetime     0.000000
passenger_count          15.542845
trip_distance             0.000000
RatecodeID               15.542845
store_and_fwd_flag       15.542845
PULocationID              0.000000
DOLocationID              0.000000
payment_type              0.000000
fare_amount               0.000000
extra                     0.000000
mta_tax                   0.000000
tip_amount                0.000000
tolls_amount              0.000000
improvement_surcharge     0.000000
total_amount              0.000000
congestion_surcharge     15.542845
Airport_fee              15.542845
cbd_congestion_fee        0.000000
dtype: float64

In [6]:
df.isnull().sum()[df.isnull().sum() > 0]

passenger_count         540149
RatecodeID              540149
store_and_fwd_flag      540149
congestion_surcharge    540149
Airport_fee             540149
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, cbd_congestion_fee]
Index: []

In [9]:
df[df["tpep_dropoff_datetime"] <= df["tpep_pickup_datetime"]]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
92,1,2025-01-01 00:49:48,2025-01-01 00:49:48,1.0,0.00,1.0,Y,87,264,2,20.06,0.0,0.0,0.0,0.00,0.0,20.06,0.0,0.0,0.00
11604,1,2025-01-01 01:42:36,2025-01-01 01:42:36,1.0,0.00,1.0,N,158,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
13820,1,2025-01-01 02:13:25,2025-01-01 02:13:25,1.0,0.00,5.0,Y,233,264,2,114.00,0.0,0.0,0.0,0.00,0.0,114.00,0.0,0.0,0.00
14605,1,2025-01-01 02:09:52,2025-01-01 02:09:52,1.0,0.00,1.0,N,237,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
14607,1,2025-01-01 02:49:40,2025-01-01 02:49:40,1.0,0.00,1.0,N,162,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3450368,1,2025-01-31 10:58:58,2025-01-31 10:58:58,NaN,0.00,NaN,None,143,143,0,13.77,0.0,0.5,0.0,0.00,1.0,15.27,NaN,NaN,0.00
3451750,6,2025-01-31 13:01:32,2025-01-31 13:01:08,NaN,8.91,NaN,None,147,137,0,2.90,0.0,0.5,0.0,6.94,0.3,32.46,NaN,NaN,0.00
3455729,2,2025-01-31 17:54:00,2025-01-31 17:54:00,NaN,0.02,NaN,None,50,50,0,-4.75,0.0,0.5,0.0,0.00,1.0,3.00,NaN,NaN,0.75
3459409,1,2025-01-31 18:55:38,2025-01-31 18:55:38,NaN,0.00,NaN,None,25,25,0,15.89,0.0,0.5,0.0,0.00,1.0,17.39,NaN,NaN,0.00
3475144,2,2025-01-31 23:44:00,2025-01-31 23:44:00,NaN,0.00,NaN,None,137,137,0,13.80,0.0,0.5,0.0,0.00,1.0,18.55,NaN,NaN,0.75

In [10]:
df[df["tpep_dropoff_datetime"] <= df["tpep_pickup_datetime"]]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
92,1,2025-01-01 00:49:48,2025-01-01 00:49:48,1.0,0.00,1.0,Y,87,264,2,20.06,0.0,0.0,0.0,0.00,0.0,20.06,0.0,0.0,0.00
11604,1,2025-01-01 01:42:36,2025-01-01 01:42:36,1.0,0.00,1.0,N,158,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
13820,1,2025-01-01 02:13:25,2025-01-01 02:13:25,1.0,0.00,5.0,Y,233,264,2,114.00,0.0,0.0,0.0,0.00,0.0,114.00,0.0,0.0,0.00
14605,1,2025-01-01 02:09:52,2025-01-01 02:09:52,1.0,0.00,1.0,N,237,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
14607,1,2025-01-01 02:49:40,2025-01-01 02:49:40,1.0,0.00,1.0,N,162,264,2,3.00,3.5,0.5,0.0,0.00,1.0,8.00,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3450368,1,2025-01-31 10:58:58,2025-01-31 10:58:58,NaN,0.00,NaN,None,143,143,0,13.77,0.0,0.5,0.0,0.00,1.0,15.27,NaN,NaN,0.00
3451750,6,2025-01-31 13:01:32,2025-01-31 13:01:08,NaN,8.91,NaN,None,147,137,0,2.90,0.0,0.5,0.0,6.94,0.3,32.46,NaN,NaN,0.00
3455729,2,2025-01-31 17:54:00,2025-01-31 17:54:00,NaN,0.02,NaN,None,50,50,0,-4.75,0.0,0.5,0.0,0.00,1.0,3.00,NaN,NaN,0.75
3459409,1,2025-01-31 18:55:38,2025-01-31 18:55:38,NaN,0.00,NaN,None,25,25,0,15.89,0.0,0.5,0.0,0.00,1.0,17.39,NaN,NaN,0.00
3475144,2,2025-01-31 23:44:00,2025-01-31 23:44:00,NaN,0.00,NaN,None,137,137,0,13.80,0.0,0.5,0.0,0.00,1.0,18.55,NaN,NaN,0.75

In [11]:
df[
    (df["fare_amount"] < 0) |
    (df["total_amount"] < 0) |
    (df["tip_amount"] < 0) |
    (df["tolls_amount"] < 0)
]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.20,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.00
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.50,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.00
104,2,2025-01-01 00:56:12,2025-01-01 01:15:00,1.0,0.97,1.0,N,161,170,4,-16.30,-1.0,-0.5,0.00,0.0,-1.0,-21.30,-2.5,0.0,0.00
149,2,2025-01-01 00:55:53,2025-01-01 01:06:49,1.0,1.42,1.0,N,79,45,2,-12.10,-1.0,-0.5,0.00,0.0,-1.0,-17.10,-2.5,0.0,0.00
202,2,2025-01-01 00:29:35,2025-01-01 00:36:02,1.0,0.60,1.0,N,79,148,4,-7.20,-1.0,-0.5,0.00,0.0,-1.0,-12.20,-2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475198,2,2025-01-31 23:30:26,2025-01-31 23:36:41,NaN,1.21,NaN,None,49,17,0,-1.50,0.0,0.5,0.00,0.0,1.0,1.00,NaN,NaN,0.00
3475204,2,2025-01-31 23:33:05,2025-01-31 23:46:21,NaN,2.55,NaN,None,144,170,0,-4.75,0.0,0.5,0.00,0.0,1.0,4.91,NaN,NaN,0.75
3475205,2,2025-01-31 23:43:55,2025-01-31 23:48:40,NaN,0.45,NaN,None,231,45,0,-4.75,0.0,0.5,0.00,0.0,1.0,3.00,NaN,NaN,0.75
3475212,2,2025-01-31 23:00:46,2025-01-31 23:12:08,NaN,1.51,NaN,None,230,229,0,-4.75,0.0,0.5,0.00,0.0,1.0,2.07,NaN,NaN,0.75
3475217,2,2025-01-31 23:38:25,2025-01-31 23:46:15,NaN,1.34,NaN,None,234,100,0,-4.75,0.0,0.5,0.00,0.0,1.0,5.00,NaN,NaN,0.75

In [12]:
df[df["passenger_count"] <= 0]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.4,1.0,N,170,170,1,4.4,3.50,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.00
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.6,1.0,N,234,148,1,12.1,3.50,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.00
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.8,1.0,N,148,170,1,19.1,3.50,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.00
94,1,2025-01-01 00:11:27,2025-01-01 00:16:58,0.0,0.7,1.0,N,144,211,1,7.2,3.50,0.5,0.00,0.0,1.0,12.20,2.5,0.0,0.00
95,1,2025-01-01 00:19:30,2025-01-01 00:27:25,0.0,1.0,1.0,N,211,158,1,9.3,3.50,0.5,2.85,0.0,1.0,17.15,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933984,1,2025-01-31 23:20:45,2025-01-31 23:45:28,0.0,3.9,1.0,N,144,50,1,25.4,4.25,0.5,2.50,0.0,1.0,33.65,2.5,0.0,0.75
2934049,1,2025-01-31 23:54:49,2025-02-01 00:09:35,0.0,6.4,1.0,N,263,232,1,28.2,4.25,0.5,2.00,0.0,1.0,35.95,2.5,0.0,0.75
2934589,1,2025-01-31 23:16:04,2025-01-31 23:36:38,0.0,2.4,1.0,N,68,114,1,15.6,4.25,0.5,4.25,0.0,1.0,25.60,2.5,0.0,0.75
2934590,1,2025-01-31 23:57:51,2025-02-01 00:08:06,0.0,1.6,1.0,N,142,236,1,10.7,3.50,0.5,3.10,0.0,1.0,18.80,2.5,0.0,0.00
2934894,1,2025-01-31 23:11:52,2025-01-31 23:37:36,0.0,6.3,1.0,N,68,112,1,29.6,4.25,0.5,5.00,0.0,1.0,40.35,2.5,0.0,0.75

In [13]:
df[df["PULocationID"].isna() | df["DOLocationID"].isna()]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, cbd_congestion_fee]
Index: []

In [14]:
registros_erroneos = df[
    (df["tpep_dropoff_datetime"] <= df["tpep_pickup_datetime"]) |
    (df["trip_distance"] < 0) |
    (df["fare_amount"] < 0) |
    (df["total_amount"] < 0) |
    (df["tip_amount"] < 0) |
    (df["tolls_amount"] < 0) |
    (df["passenger_count"] <= 0) |
    (df["PULocationID"].isna()) |
    (df["DOLocationID"].isna())
]

registros_erroneos

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.40,1.0,N,170,170,1,4.40,3.5,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.00
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.60,1.0,N,234,148,1,12.10,3.5,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.00
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.80,1.0,N,148,170,1,19.10,3.5,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.00
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.20,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.00
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.50,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475198,2,2025-01-31 23:30:26,2025-01-31 23:36:41,NaN,1.21,NaN,None,49,17,0,-1.50,0.0,0.5,0.00,0.0,1.0,1.00,NaN,NaN,0.00
3475204,2,2025-01-31 23:33:05,2025-01-31 23:46:21,NaN,2.55,NaN,None,144,170,0,-4.75,0.0,0.5,0.00,0.0,1.0,4.91,NaN,NaN,0.75
3475205,2,2025-01-31 23:43:55,2025-01-31 23:48:40,NaN,0.45,NaN,None,231,45,0,-4.75,0.0,0.5,0.00,0.0,1.0,3.00,NaN,NaN,0.75
3475212,2,2025-01-31 23:00:46,2025-01-31 23:12:08,NaN,1.51,NaN,None,230,229,0,-4.75,0.0,0.5,0.00,0.0,1.0,2.07,NaN,NaN,0.75
3475217,2,2025-01-31 23:38:25,2025-01-31 23:46:15,NaN,1.34,NaN,None,234,100,0,-4.75,0.0,0.5,0.00,0.0,1.0,5.00,NaN,NaN,0.75

In [15]:
len(registros_erroneos)

170939

In [16]:
len(registros_erroneos) / len(df) * 100

4.918788015513235

In [17]:
registros_erroneos = df[
    (df["tpep_dropoff_datetime"] <= df["tpep_pickup_datetime"]) |
    (df["trip_distance"] < 0) |
    (df["fare_amount"] < 0) |
    (df["total_amount"] < 0) |
    (df["tip_amount"] < 0) |
    (df["tolls_amount"] < 0) |
    (df["passenger_count"] <= 0) |
    (df["PULocationID"].isna()) |
    (df["DOLocationID"].isna())
]

print("Total registros erróneos:", len(registros_erroneos))
print("Porcentaje:", round(len(registros_erroneos) / len(df) * 100, 4), "%")

Total registros erróneos: 170939
Porcentaje: 4.9188 %